module.exports = [
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '50,00',
        payer: 'Miha',
        payDate: '2021-02-01',
        description: 'BMW - gorivo',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Lekarna',
        cost: '44,00',
        payer: 'Nataša',
        payDate: '2021-02-01',
        description: 'Zdravila in krema za vimene',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '91,00',
        payer: 'Nataša',
        payDate: '2020-04-01',
        description: 'Hrana med Karanteno',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '10,00',
        payer: 'Nataša',
        payDate: '2021-04-01',
        description: 'Jajca in hrana',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '12,00',
        payer: 'Miha',
        payDate: '2022-06-01',
        description: 'Kosilo Bohinj-Štrudl',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '17,80',
        payer: 'Miha',
        payDate: '2022-06-01',
        description: 'Maharaja',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '18,00',
        payer: 'Miha',
        payDate: '2021-07-01',
        description: 'Maharađa',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '240,00',
        payer: 'Nataša',
        payDate: '2021-07-01',
        description: 'Razvlaževalnik Qlima',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '102,90',
        payer: 'Nataša',
        payDate: '2021-09-01',
        description: 'nordic nest',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '9,57',
        payer: 'Miha',
        payDate: '2021-10-01',
        description: 'Spar',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '8,00',
        payer: 'Nataša',
        payDate: '2020-12-01',
        description: 'jogurt, kruh',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '70,00',
        payer: 'Miha',
        payDate: '2022-01-02',
        description: 'BMW - Gorivo',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '30,00',
        payer: 'Miha',
        payDate: '2021-04-02',
        description: 'SPAR',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '36,00',
        payer: 'Nataša',
        payDate: '2022-04-02',
        description: 'Harvey Norman',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '20,80',
        payer: 'Nataša',
        payDate: '2022-06-02',
        description: 'Hrana Bohinj-Štrudl',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '55,00',
        payer: 'Nataša',
        payDate: '2020-07-02',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '128,67',
        payer: 'Miha',
        payDate: '2021-07-02',
        description:
            'Miele - servis pomivalni (NTC, Nepovratni ventil, tesnilo za lesk))',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '250,00',
        payer: 'Miha',
        payDate: '2021-07-02',
        description: 'Slikce  - okvirji',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '23,00',
        payer: 'Miha',
        payDate: '2021-07-02',
        description: 'Dobra Vila Pizza',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '35,00',
        payer: 'Miha',
        payDate: '2021-08-02',
        description: 'Lora - dihtnge',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Moda',
        cost: '37,00',
        payer: 'Miha',
        payDate: '2021-08-02',
        description: 'Lora - rjuhe',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '17,00',
        payer: 'Nataša',
        payDate: '2021-08-02',
        description: 'Skute',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '2,30',
        payer: 'Nataša',
        payDate: '2021-10-02',
        description: 'DM',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '2,00',
        payer: 'Nataša',
        payDate: '2020-12-02',
        description: 'jajca',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '34,36',
        payer: 'Nataša',
        payDate: '2021-12-02',
        description: 'Spar',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '88,16',
        payer: 'Nataša',
        payDate: '2022-01-03',
        description: 'Lora - Vet',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '47,03',
        payer: 'Nataša',
        payDate: '2022-01-03',
        description: 'Lora - Hrana',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '20,00',
        payer: 'Nataša',
        payDate: '2022-02-03',
        description: 'Hrana ',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '70,00',
        payer: 'Nataša',
        payDate: '2021-03-03',
        description: 'Lora - zdravila',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '115,63',
        payer: 'Miha',
        payDate: '2022-03-03',
        description: 'Panda Mini Advanced Fuzzy Logic Ceramic Rice Cooker ',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '96,48',
        payer: 'Miha',
        payDate: '2022-05-03',
        description: 'Lora - vetmedin',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '13,28',
        payer: 'Nataša',
        payDate: '2022-05-03',
        description: 'Lora - vetmedin',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '13,00',
        payer: 'Nataša',
        payDate: '2020-06-03',
        description: 'Jajca in skuta',
        shared: true,
    },
    {
        category: 'Zabava',
        subCategory: 'Dopust',
        cost: '46,40',
        payer: 'Miha',
        payDate: '2022-06-03',
        description: 'Hotel Bohinj',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '30,00',
        payer: 'Miha',
        payDate: '2022-06-03',
        description: 'Kava in čokolada',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '17,40',
        payer: 'Nataša',
        payDate: '2021-07-03',
        description: 'Skute in zelenjava',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '47,00',
        payer: 'Nataša',
        payDate: '2021-07-03',
        description: 'Mol - BMW tank',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '37,00',
        payer: 'Nataša',
        payDate: '2019-10-03',
        description: 'Med',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '10,28',
        payer: 'Nataša',
        payDate: '2021-11-03',
        description: 'DM',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '179,11',
        payer: 'Miha',
        payDate: '2022-01-04',
        description: 'Lora - Pregled',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Pnevmatike',
        cost: '333,46',
        payer: 'Nataša',
        payDate: '2021-03-04',
        description: 'BMW - Letne gume DOT 4920',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '5,00',
        payer: 'Nataša',
        payDate: '2021-03-04',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '14,69',
        payer: 'Nataša',
        payDate: '2022-04-04',
        description: 'Spar',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '10,50',
        payer: 'Nataša',
        payDate: '2021-05-04',
        description: 'Lora - Vetmedin',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '48,84',
        payer: 'Nataša',
        payDate: '2021-05-04',
        description: 'Lora - Hrana',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '22,00',
        payer: 'Nataša',
        payDate: '2021-05-04',
        description: 'Lora - Zdravila',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '42,79',
        payer: 'Nataša',
        payDate: '2021-05-04',
        description: 'BMW - Tank',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '5,00',
        payer: 'Nataša',
        payDate: '2022-05-04',
        description: 'Jajca in jogurti',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Mercator',
        cost: '28,00',
        payer: 'Nataša',
        payDate: '2020-06-04',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '5,00',
        payer: 'Nataša',
        payDate: '2020-06-04',
        description: 'Jagode',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '23,50',
        payer: 'Nataša',
        payDate: '2019-11-04',
        description: 'IKEA',
        shared: true,
    },
    {
        category: 'Hobi',
        subCategory: 'Kolesarstvo',
        cost: '650,00',
        payer: 'Miha',
        payDate: '2019-11-04',
        description: 'Trenažer ELITE DIRETO X',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '2,50',
        payer: 'Nataša',
        payDate: '2020-11-04',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Zabava',
        subCategory: 'Dopust',
        cost: '175,10',
        payer: 'Nataša',
        payDate: '2021-11-04',
        description: 'Rimske Toplice',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '10,70',
        payer: 'Nataša',
        payDate: '2021-11-04',
        description: 'PICA',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '19,98',
        payer: 'Nataša',
        payDate: '2021-12-04',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '8,32',
        payer: 'Miha',
        payDate: '2021-12-04',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '78,84',
        payer: 'Miha',
        payDate: '2021-12-04',
        description: 'IKEA',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '80,00',
        payer: 'Nataša',
        payDate: '2021-01-05',
        description: 'Trgovina - Hofer',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '34,04',
        payer: 'Miha',
        payDate: '2022-04-05',
        description: 'BMW - GORIVO',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '6,20',
        payer: 'Nataša',
        payDate: '2020-05-05',
        description: 'Skuta',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '89,86',
        payer: 'Miha',
        payDate: '2021-05-05',
        description: '',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '61,82',
        payer: 'Miha',
        payDate: '2021-05-05',
        description: 'Lora - Pregled krvi',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '9,66',
        payer: 'Nataša',
        payDate: '2021-08-05',
        description: 'DM',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '10,00',
        payer: 'Nataša',
        payDate: '2019-11-05',
        description: 'Prašek',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '3,00',
        payer: 'Miha',
        payDate: '2020-11-05',
        description: 'Kis',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '57,43',
        payer: 'Miha',
        payDate: '2021-12-05',
        description: 'BAUHAUS',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tuš',
        cost: '56,67',
        payer: 'Miha',
        payDate: '2021-02-06',
        description: 'Tuš, fasnga',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '10,00',
        payer: 'Nataša',
        payDate: '2021-02-06',
        description: 'jogurti in skute',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Zavarovanje',
        cost: '410,65',
        payer: 'Nataša',
        payDate: '2020-05-06',
        description: 'BMW - Zavarovanje',
        shared: true,
    },
    {
        category: 'Clio',
        subCategory: 'Gorivo',
        cost: '45,73',
        payer: 'Nataša',
        payDate: '2021-05-06',
        description: 'Clio - Gorivo',
        shared: true,
    },
    {
        category: 'Darila',
        subCategory: 'Prijatelji',
        cost: '50,00',
        payer: 'Nataša',
        payDate: '2022-06-06',
        description: 'Darilo - Nel',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Lekarna',
        cost: '3,20',
        payer: 'Nataša',
        payDate: '2021-07-06',
        description: 'Lekarna',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '33,78',
        payer: 'Nataša',
        payDate: '2021-07-06',
        description: 'SPAR',
        shared: true,
    },
    {
        category: 'Clio',
        subCategory: 'Zavarovanje',
        cost: '169,12',
        payer: 'Miha',
        payDate: '2019-11-06',
        description: 'Zavarovanje Clio',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '87,94',
        payer: 'Nataša',
        payDate: '2021-11-06',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '16,94',
        payer: 'Nataša',
        payDate: '2021-11-06',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Mercator',
        cost: '26,27',
        payer: 'Miha',
        payDate: '2021-12-06',
        description: 'MERCATOR',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '147,10',
        payer: 'Miha',
        payDate: '2021-12-06',
        description: 'Lora - zdravila',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '19,00',
        payer: 'Nataša',
        payDate: '2022-01-07',
        description: 'Lora - zdravila',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '83,00',
        payer: 'Miha',
        payDate: '2020-03-07',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '49,00',
        payer: 'Nataša',
        payDate: '2021-03-07',
        description: 'SPAR, HOFER, DM',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '104,00',
        payer: 'Miha',
        payDate: '2022-03-07',
        description: 'IKEA - Košare',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '34,00',
        payer: 'Nataša',
        payDate: '2022-03-07',
        description: 'Lora - zdravila',
        shared: true,
    },
    {
        category: 'Clio',
        subCategory: 'Gorivo',
        cost: '54,00',
        payer: 'Nataša',
        payDate: '2022-03-07',
        description: 'Clio - benz',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '8,00',
        payer: 'Nataša',
        payDate: '2022-03-07',
        description: 'Tržnica',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '10,00',
        payer: 'Nataša',
        payDate: '2022-04-07',
        description: 'Tržnica',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '31,00',
        payer: 'Nataša',
        payDate: '2022-05-07',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '14,04',
        payer: 'Nataša',
        payDate: '2022-05-07',
        description: '',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Moda',
        cost: '50,00',
        payer: 'Miha',
        payDate: '2022-05-07',
        description: 'Lora - frizer',
        shared: true,
    },
    {
        category: 'Darila',
        subCategory: 'Prijatelji',
        cost: '60,00',
        payer: 'Miha',
        payDate: '2022-05-07',
        description: 'Darilo Mato(Escape room bon)',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '2,50',
        payer: 'Nataša',
        payDate: '2022-06-07',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '150,00',
        payer: 'Nataša',
        payDate: '2022-06-07',
        description: 'Lora - pregled in zdravila',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '24,14',
        payer: 'Nataša',
        payDate: '2021-08-07',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '14,66',
        payer: 'Nataša',
        payDate: '2021-08-07',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '8,06',
        payer: 'Nataša',
        payDate: '2021-08-07',
        description: 'SPAR',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '5,00',
        payer: 'Nataša',
        payDate: '2020-10-07',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '68,18',
        payer: 'Miha',
        payDate: '2021-10-07',
        description: 'BMW - Mol',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '30,34',
        payer: 'Miha',
        payDate: '2021-10-07',
        description: 'Hofer',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '21,00',
        payer: 'Miha',
        payDate: '2021-10-07',
        description: 'Hrana',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '15,00',
        payer: 'Nataša',
        payDate: '2021-10-07',
        description: 'Jajca in med',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '10,00',
        payer: 'Nataša',
        payDate: '2020-11-07',
        description: 'Jogurti',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '150,00',
        payer: 'Nataša',
        payDate: '2020-12-07',
        description: 'Lora - pregled, zdravila in hrana (vnetje želodca)',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '53,33',
        payer: 'Miha',
        payDate: '2020-12-07',
        description: 'BMW - gorivo',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '13,00',
        payer: 'Nataša',
        payDate: '2021-01-08',
        description: 'Trgovina',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '49,34',
        payer: 'Miha',
        payDate: '2022-01-08',
        description: 'Spar',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '97,40',
        payer: 'Nataša',
        payDate: '2022-03-08',
        description: 'Lora - pregled',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '95,23',
        payer: 'Nataša',
        payDate: '2022-06-08',
        description: '',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '40,00',
        payer: 'Nataša',
        payDate: '2021-09-08',
        description: 'Lora - Hrana',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '12,89',
        payer: 'Miha',
        payDate: '2021-09-08',
        description: 'Roomba - Filtri',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '20,00',
        payer: 'Nataša',
        payDate: '2021-01-09',
        description: 'Tržnica',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Moda',
        cost: '50,00',
        payer: 'Miha',
        payDate: '2021-01-09',
        description: 'Lora - Frizerka Tina',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '42,91',
        payer: 'Miha',
        payDate: '2021-02-09',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '10,00',
        payer: 'Nataša',
        payDate: '2020-04-09',
        description: 'Jajca in skuta',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '470,00',
        payer: 'Miha',
        payDate: '2022-05-09',
        description: 'Omara - predelava predalnikov',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '43,84',
        payer: 'Miha',
        payDate: '2022-06-09',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Mercator',
        cost: '8,20',
        payer: 'Nataša',
        payDate: '2020-07-09',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '5,00',
        payer: 'Nataša',
        payDate: '2020-07-09',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '25,00',
        payer: 'Nataša',
        payDate: '2020-07-09',
        description: 'FlapJack',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '18,87',
        payer: 'Nataša',
        payDate: '2021-07-09',
        description: 'HOFER',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '22,14',
        payer: 'Miha',
        payDate: '2021-09-09',
        description: 'BAUHAUS - orodje',
        shared: true,
    },
    {
        category: 'Clio',
        subCategory: 'Gorivo',
        cost: '58,36',
        payer: 'Nataša',
        payDate: '2021-09-09',
        description: 'Mol',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '24,45',
        payer: 'Miha',
        payDate: '2021-09-09',
        description: 'DM',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '2,50',
        payer: 'Nataša',
        payDate: '2021-10-09',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Clio',
        subCategory: 'Registracija',
        cost: '107,48',
        payer: 'Nataša',
        payDate: '2019-11-09',
        description: 'Registracija Clio',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '113,00',
        payer: 'Nataša',
        payDate: '2020-11-09',
        description: 'Vzglavniki',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Zavarovanje',
        cost: '465,74',
        payer: 'Nataša',
        payDate: '2021-11-09',
        description: 'BMW - Zavarovanje',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '29,70',
        payer: 'Nataša',
        payDate: '2022-01-10',
        description: 'Lora - veterinar',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '30,00',
        payer: 'Nataša',
        payDate: '2022-01-10',
        description: 'Lora - zdravila',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Vzdrževanje',
        cost: '200,00',
        payer: 'Nataša',
        payDate: '2021-02-10',
        description: 'BMW - Servis, mali',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '10,00',
        payer: 'Miha',
        payDate: '2022-04-10',
        description: 'Tržnica',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '12,96',
        payer: 'Miha',
        payDate: '2019-09-10',
        description: 'Interkalarne obresti kredita',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '34,00',
        payer: 'Nataša',
        payDate: '2019-10-10',
        description: '',
        shared: true,
    },
    {
        category: 'Clio',
        subCategory: 'Zavarovanje',
        cost: '231,65',
        payer: 'Nataša',
        payDate: '2021-11-10',
        description: 'Clio - Zavarovanje',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '2,50',
        payer: 'Nataša',
        payDate: '2021-11-10',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '60,61',
        payer: 'Nataša',
        payDate: '2021-01-11',
        description: 'Lora - cepljenje',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Vzdrževanje',
        cost: '209,00',
        payer: 'Miha',
        payDate: '2022-02-11',
        description: 'BMW - Servis(olje in filtri, AirBag)',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '170,00',
        payer: 'Nataša',
        payDate: '2021-04-11',
        description: 'Lora - Vet, srček :/',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '23,50',
        payer: 'Nataša',
        payDate: '2020-05-11',
        description: 'Jagode, skuta, jajca',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '54,80',
        payer: 'Nataša',
        payDate: '2021-05-11',
        description: 'Pizza - Trapa (Joc, Nel, Jaz)',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '42,50',
        payer: 'Miha',
        payDate: '2021-06-11',
        description: 'Dimnikar 2021',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '8,00',
        payer: 'Nataša',
        payDate: '2021-07-11',
        description: 'Zelenjava',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '58,36',
        payer: 'Nataša',
        payDate: '2021-09-11',
        description: 'BMW - Gorivo',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '39,94',
        payer: 'Nataša',
        payDate: '2021-09-11',
        description: 'Lora - Hrana',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Moda',
        cost: '50,00',
        payer: 'Nataša',
        payDate: '2021-11-11',
        description: 'Lora - Frizer',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '51,00',
        payer: 'Nataša',
        payDate: '2021-11-11',
        description: 'Med',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '5,00',
        payer: 'Nataša',
        payDate: '2021-12-11',
        description: 'Tržnica',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '30,00',
        payer: 'Miha',
        payDate: '2021-12-11',
        description: 'Tržnica',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Moda',
        cost: '80,00',
        payer: 'Nataša',
        payDate: '2021-01-12',
        description: 'Lora - oprsnica',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '12,66',
        payer: 'Miha',
        payDate: '2021-02-12',
        description: 'Gumbi z vijaki - žaluzije',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '37,00',
        payer: 'Nataša',
        payDate: '2021-02-12',
        description: 'Lora - Zdravila',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '89,48',
        payer: 'Nataša',
        payDate: '2021-04-12',
        description: 'Lora - Hrana',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '1,00',
        payer: 'Nataša',
        payDate: '2021-04-12',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '20,00',
        payer: 'Nataša',
        payDate: '2021-04-12',
        description: 'Lora - zdravila',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '100,40',
        payer: 'Nataša',
        payDate: '2022-04-12',
        description: 'Lora - Veterinar in zdravila',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Pnevmatike',
        cost: '64,00',
        payer: 'Nataša',
        payDate: '2022-05-12',
        description: 'BMW - Menjava gum 50 - 14(hramba)',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Zavarovanje',
        cost: '239,27',
        payer: 'Nataša',
        payDate: '2022-05-12',
        description:
            'BMW - zavarobvanje, plačilo razlike za uskladitev datumov zav. in reg.',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '13,00',
        payer: 'Miha',
        payDate: '2020-12-12',
        description: 'Skute in mlečni izdelki',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'E.Leclerc',
        cost: '16,25',
        payer: 'Miha',
        payDate: '2021-01-13',
        description: 'Razvajanje iz E.Leclerc',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '64,75',
        payer: 'Miha',
        payDate: '2020-03-13',
        description: '',
        shared: true,
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: '2,80',
        payer: 'Nataša',
        payDate: '2021-05-13',
        description: 'Poštnina za darilo, Slatna',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '43,70',
        payer: 'Miha',
        payDate: '2022-05-13',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '22,00',
        payer: 'Nataša',
        payDate: '2020-06-13',
        description: 'Skuta',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '5,00',
        payer: 'Nataša',
        payDate: '2020-08-13',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '45,93',
        payer: 'Miha',
        payDate: '2021-08-13',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '34,45',
        payer: 'Miha',
        payDate: '2019-09-13',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '51,35',
        payer: 'Miha',
        payDate: '2020-11-13',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '33,71',
        payer: 'Miha',
        payDate: '2019-12-13',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '44,66',
        payer: 'Miha',
        payDate: '2020-02-14',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '49,27',
        payer: 'Miha',
        payDate: '2021-05-14',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '20,76',
        payer: 'Miha',
        payDate: '2022-05-14',
        description: '',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '44,00',
        payer: 'Miha',
        payDate: '2022-06-14',
        description: 'Lora - zdravila',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '47,64',
        payer: 'Miha',
        payDate: '2020-08-14',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '45,33',
        payer: 'Nataša',
        payDate: '2021-09-14',
        description: 'SPAR',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '34,45',
        payer: 'Miha',
        payDate: '2019-10-14',
        description: '',
        shared: true,
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: '15,00',
        payer: 'Nataša',
        payDate: '2021-10-14',
        description: 'Torticeee',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '33,71',
        payer: 'Miha',
        payDate: '2019-11-14',
        description: '',
        shared: true,
    },
    {
        category: 'Clio',
        subCategory: 'Vzdrževanje',
        cost: '80,00',
        payer: 'Miha',
        payDate: '2020-11-14',
        description: 'Mali servis Clio, luči, olje, tekočine, manšete',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '28,50',
        payer: 'Miha',
        payDate: '2021-11-14',
        description: 'Lora - lanitop',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '49,49',
        payer: 'Miha',
        payDate: '2020-12-14',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '49,49',
        payer: 'Miha',
        payDate: '2021-01-15',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '49,77',
        payer: 'Miha',
        payDate: '2021-02-15',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '46,25',
        payer: 'Miha',
        payDate: '2022-02-15',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '51,01',
        payer: 'Miha',
        payDate: '2021-03-15',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '20,00',
        payer: 'Nataša',
        payDate: '2021-03-15',
        description: 'Tržnica',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '33,96',
        payer: 'Miha',
        payDate: '2022-03-15',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '48,31',
        payer: 'Miha',
        payDate: '2020-04-15',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '4,00',
        payer: 'Miha',
        payDate: '2020-04-15',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '49,42',
        payer: 'Miha',
        payDate: '2021-04-15',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '48,31',
        payer: 'Miha',
        payDate: '2020-05-15',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '52,00',
        payer: 'Miha',
        payDate: '2020-05-15',
        description: 'Meso(20), Suho sadje(32)',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '47,64',
        payer: 'Miha',
        payDate: '2020-06-15',
        description: '',
        shared: true,
    },
    {
        category: 'Zabava',
        subCategory: 'Dopust',
        cost: '50,00',
        payer: 'Nataša',
        payDate: '2020-06-15',
        description: 'Menjava kun',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '46,83',
        payer: 'Miha',
        payDate: '2021-06-15',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '48,20',
        payer: 'Miha',
        payDate: '2022-06-15',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '47,64',
        payer: 'Miha',
        payDate: '2020-07-15',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '46,22',
        payer: 'Miha',
        payDate: '2021-07-15',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '55,06',
        payer: 'Miha',
        payDate: '2020-09-15',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '47,64',
        payer: 'Miha',
        payDate: '2020-10-15',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '20,00',
        payer: 'Miha',
        payDate: '2020-11-15',
        description: 'Bučno olje',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '5,10',
        payer: 'Nataša',
        payDate: '2020-11-15',
        description: 'Skute, kruh, jogurt',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '46,59',
        payer: 'Miha',
        payDate: '2021-11-15',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '10,00',
        payer: 'Nataša',
        payDate: '2021-11-15',
        description: 'Tržnica',
        shared: true,
    },
    {
        category: 'Hobi',
        subCategory: 'Plezanje',
        cost: '275,00',
        payer: 'Miha',
        payDate: '2020-01-16',
        description: 'Plezanje Miško, December, januar do 14.februarja',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '10,00',
        payer: 'Nataša',
        payDate: '2022-02-16',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '6,20',
        payer: 'Nataša',
        payDate: '2020-04-16',
        description: 'Skuta',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '11,30',
        payer: 'Nataša',
        payDate: '2021-05-16',
        description: 'Lora - Edemid',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Registracija',
        cost: '199,00',
        payer: 'Miha',
        payDate: '2022-05-16',
        description: 'BMW - Tehnični in registracija',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '2,50',
        payer: 'Nataša',
        payDate: '2021-06-16',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Lekarna',
        cost: '8,20',
        payer: 'Nataša',
        payDate: '2021-06-16',
        description: 'Krema za sunčanje',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '10,00',
        payer: 'Nataša',
        payDate: '2021-06-16',
        description: 'MED',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '42,37',
        payer: 'Miha',
        payDate: '2021-09-16',
        description: '',
        shared: true,
    },
    {
        category: 'Clio',
        subCategory: 'Zavarovanje',
        cost: '127,98',
        payer: 'Nataša',
        payDate: '2020-11-16',
        description: 'Zavarovanje Clio',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '79,88',
        payer: 'Nataša',
        payDate: '2021-11-16',
        description: 'Lora - klobase',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '19,00',
        payer: 'Miha',
        payDate: '2021-11-16',
        description: 'Kosilo',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Registracija',
        cost: '83,42',
        payer: 'Nataša',
        payDate: '2022-01-17',
        description: 'BMW - Registracija (poziv pred odjavo iz prometa)',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '95,40',
        payer: 'Nataša',
        payDate: '2022-02-17',
        description: 'ARTLES - dva stola(mala)',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-05-17',
        description: '',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Registracija',
        cost: '120,00',
        payer: 'Nataša',
        payDate: '2021-05-17',
        description: 'BMW - registracija in tehnični pregled',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '50,00',
        payer: 'Nataša',
        payDate: '2022-05-17',
        description: 'Lora - hrana',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Vzdrževanje',
        cost: '10,00',
        payer: 'Nataša',
        payDate: '2020-06-17',
        description: 'BMW - pregled zadnjih enkoderjev [ABS]',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '47,03',
        payer: 'Miha',
        payDate: '2021-09-17',
        description: 'BMW - gorivo',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '41,28',
        payer: 'Miha',
        payDate: '2021-09-17',
        description: 'SPAR - Hrana',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '37,05',
        payer: 'Nataša',
        payDate: '2021-05-17',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '31,45',
        payer: 'Nataša',
        payDate: '2020-01-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2020-01-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '47,54',
        payer: 'Nataša',
        payDate: '2021-01-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2022-01-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2022-01-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '47,96',
        payer: 'Nataša',
        payDate: '2022-01-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '41,65',
        payer: 'Miha',
        payDate: '2022-01-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2020-02-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '34,07',
        payer: 'Nataša',
        payDate: '2020-02-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2021-02-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '45,40',
        payer: 'Nataša',
        payDate: '2021-02-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2022-02-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '48,57',
        payer: 'Nataša',
        payDate: '2022-02-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2022-02-18',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '2,00',
        payer: 'Nataša',
        payDate: '2022-02-18',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2020-03-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '32,10',
        payer: 'Nataša',
        payDate: '2020-03-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2021-03-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '39,25',
        payer: 'Nataša',
        payDate: '2021-03-18',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '32,00',
        payer: 'Miha',
        payDate: '2021-03-18',
        description: 'Kis in bučno olje.',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2022-03-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2022-03-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '17,54',
        payer: 'Nataša',
        payDate: '2022-03-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2020-04-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2021-04-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2022-04-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '25,23',
        payer: 'Nataša',
        payDate: '2020-05-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2020-05-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2021-05-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2022-05-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2022-05-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '17,53',
        payer: 'Nataša',
        payDate: '2022-05-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2020-06-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '21,06',
        payer: 'Nataša',
        payDate: '2020-06-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '42,50',
        payer: 'Nataša',
        payDate: '2020-06-18',
        description: 'Dimnikar',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-06-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '36,19',
        payer: 'Nataša',
        payDate: '2021-06-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2021-06-18',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '29,85',
        payer: 'Miha',
        payDate: '2021-06-18',
        description: 'Lars&Sven',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2022-06-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2021-07-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '3030-07-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2020-08-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '35,05',
        payer: 'Nataša',
        payDate: '2020-08-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '203,99',
        payer: 'Nataša',
        payDate: '2020-08-18',
        description: 'Cenitev stanovanja',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '53,60',
        payer: 'Miha',
        payDate: '2020-08-18',
        description: 'Servis peči - letni pregled',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '10,00',
        payer: 'Nataša',
        payDate: '2020-08-18',
        description: 'Vinkulacija',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '204,01',
        payer: 'Nataša',
        payDate: '2020-08-18',
        description: 'Zavarovanje stanovanja',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2021-08-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '38,17',
        payer: 'Nataša',
        payDate: '2021-08-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '204,01',
        payer: 'Nataša',
        payDate: '2021-08-18',
        description: 'Zavarovanje stanovanja',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '34,87',
        payer: 'Nataša',
        payDate: '2020-09-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2020-09-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2021-09-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '31,32',
        payer: 'Nataša',
        payDate: '2021-09-18',
        description: 'Ponev',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '27,78',
        payer: 'Nataša',
        payDate: '2019-10-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '30,00',
        payer: 'Nataša',
        payDate: '2019-10-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2020-10-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-10-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2021-10-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '45,08',
        payer: 'Miha',
        payDate: '2021-10-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '36,12',
        payer: 'Nataša',
        payDate: '2021-10-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '30,00',
        payer: 'Nataša',
        payDate: '2019-11-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '29,69',
        payer: 'Nataša',
        payDate: '2019-11-18',
        description: '',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Vzdrževanje',
        cost: '128,00',
        payer: 'Miha',
        payDate: '2019-11-18',
        description: 'BMW - servis - olje, filtri',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2020-11-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '42,53',
        payer: 'Nataša',
        payDate: '2020-11-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-11-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2021-11-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '38,92',
        payer: 'Nataša',
        payDate: '2021-11-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '30,00',
        payer: 'Nataša',
        payDate: '2019-12-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '32,83',
        payer: 'Nataša',
        payDate: '2019-12-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '45,19',
        payer: 'Nataša',
        payDate: '2020-12-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2020-12-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '35,00',
        payer: 'Nataša',
        payDate: '2021-12-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '45,18',
        payer: 'Miha',
        payDate: '2021-12-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '40,82',
        payer: 'Nataša',
        payDate: '2021-04-19',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '19,63',
        payer: 'Nataša',
        payDate: '2022-04-19',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2022-04-19',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '44,96',
        payer: 'Miha',
        payDate: '2022-04-19',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '11,10',
        payer: 'Nataša',
        payDate: '2022-05-19',
        description: 'Jogurti in jajca',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '20,90',
        payer: 'Miha',
        payDate: '2020-06-19',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-07-19',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '35,60',
        payer: 'Nataša',
        payDate: '2021-07-19',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '213,50',
        payer: 'Miha',
        payDate: '2019-08-19',
        description: 'Cenitev stanovanja',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '31,23',
        payer: 'Nataša',
        payDate: '2019-08-19',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-08-19',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '36,04',
        payer: 'Nataša',
        payDate: '2020-10-19',
        description: '',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Zavarovanje',
        cost: '424,48',
        payer: 'Miha',
        payDate: '2020-11-19',
        description: 'BMW - novo zavarovanje (prestavitev na Natašo)',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '10,00',
        payer: 'Nataša',
        payDate: '2020-12-19',
        description: 'Skute in mlečni izdelki',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '33,31',
        payer: 'Nataša',
        payDate: '2020-01-20',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '44,14',
        payer: 'Miha',
        payDate: '2021-02-20',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '23,07',
        payer: 'Miha',
        payDate: '2020-03-20',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '34,55',
        payer: 'Miha',
        payDate: '2021-03-20',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '24,10',
        payer: 'Nataša',
        payDate: '2020-04-20',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '5,00',
        payer: 'Nataša',
        payDate: '2020-05-20',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2022-06-21',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '39,14',
        payer: 'Nataša',
        payDate: '2022-06-20',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '29,41',
        payer: 'Nataša',
        payDate: '2020-07-20',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '8,71',
        payer: 'Nataša',
        payDate: '2019-09-20',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '27,63',
        payer: 'Nataša',
        payDate: '2019-09-20',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '35,56',
        payer: 'Nataša',
        payDate: '2021-09-20',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-09-20',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '25,89',
        payer: 'Miha',
        payDate: '2020-11-20',
        description: '',
        shared: true,
    },
    {
        category: 'Clio',
        subCategory: 'Pnevmatike',
        cost: '96,94',
        payer: 'Nataša',
        payDate: '2020-11-20',
        description: 'Gume Clio (Sprednji zimski)',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Registracija',
        cost: '33,40',
        payer: 'Nataša',
        payDate: '2020-11-20',
        description: 'BMW - Prepis in cestnina (Prepis na Natašo)',
        shared: true,
    },
    {
        category: 'Clio',
        subCategory: 'Registracija',
        cost: '105,99',
        payer: 'Nataša',
        payDate: '2020-11-20',
        description: 'Registracij in tehnični pregled Clio',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '23,20',
        payer: 'Miha',
        payDate: '2019-12-20',
        description: '',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Vzdrževanje',
        cost: '1246,98',
        payer: 'Nataša',
        payDate: '2019-12-20',
        description: 'BMW - servis - veriga, jermen, izpuh(fleksibilni del)',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-12-20',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '36,99',
        payer: 'Nataša',
        payDate: '2021-12-20',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '35,54',
        payer: 'Miha',
        payDate: '2020-01-21',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '48,87',
        payer: 'Miha',
        payDate: '2022-01-21',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '37,60',
        payer: 'Miha',
        payDate: '2020-02-21',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '5,00',
        payer: 'Nataša',
        payDate: '2020-04-21',
        description: 'Skuta',
        shared: true,
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: '15,90',
        payer: 'Nataša',
        payDate: '2022-05-21',
        description: 'Majica Žiga',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '15,00',
        payer: 'Nataša',
        payDate: '2022-05-21',
        description: 'Jagode + kruh ',
        shared: true,
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: '20,00',
        payer: 'Miha',
        payDate: '2022-05-21',
        description: 'Majica Jaka',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '18,52',
        payer: 'Miha',
        payDate: '2020-07-21',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '17,40',
        payer: 'Miha',
        payDate: '2021-07-21',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '13,68',
        payer: 'Miha',
        payDate: '2021-08-21',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '14,34',
        payer: 'Miha',
        payDate: '2021-09-21',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '21,39',
        payer: 'Miha',
        payDate: '2020-10-21',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '162,25',
        payer: 'Miha',
        payDate: '2020-02-22',
        description: 'IKEA: Stoli, krožniki, luč...',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '52,61',
        payer: 'Miha',
        payDate: '2022-02-22',
        description: '',
        shared: true,
    },
    {
        category: 'Darila',
        subCategory: 'Prijatelji',
        cost: '50,68',
        payer: 'Nataša',
        payDate: '2022-02-22',
        description: 'Igre - majino darilo',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '26,49',
        payer: 'Miha',
        payDate: '2020-04-22',
        description: '',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '113,00',
        payer: 'Miha',
        payDate: '2021-04-22',
        description: 'Lora - Vetmedin',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '27,54',
        payer: 'Miha',
        payDate: '2021-05-22',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '23,92',
        payer: 'Miha',
        payDate: '2021-06-22',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '18,58',
        payer: 'Nataša',
        payDate: '2019-08-22',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '17,98',
        payer: 'Miha',
        payDate: '2020-08-22',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '17,91',
        payer: 'Miha',
        payDate: '2020-09-22',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '16,48',
        payer: 'Miha',
        payDate: '2019-10-22',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '15,48',
        payer: 'Miha',
        payDate: '2021-10-22',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '67,00',
        payer: 'Miha',
        payDate: '2021-10-22',
        description: 'Servis preči - letni pregled',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '19,84',
        payer: 'Miha',
        payDate: '2019-11-22',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '29,84',
        payer: 'Miha',
        payDate: '2020-12-22',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '24,50',
        payer: 'Miha',
        payDate: '2021-12-22',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '10,00',
        payer: 'Nataša',
        payDate: '2021-01-23',
        description: 'Skute in jogurti',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Lekarna',
        cost: '15,00',
        payer: 'Nataša',
        payDate: '2022-01-23',
        description: 'Testi',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '10,50',
        payer: 'Nataša',
        payDate: '2022-01-23',
        description: 'Jogurti, sir, skuta',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '32,17',
        payer: 'Miha',
        payDate: '2021-04-23',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '19,70',
        payer: 'Miha',
        payDate: '2020-05-23',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '20,83',
        payer: 'Miha',
        payDate: '2022-06-23',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '39,46',
        payer: 'Miha',
        payDate: '2019-08-23',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '12,90',
        payer: 'Miha',
        payDate: '2019-08-23',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '22,50',
        payer: 'Miha',
        payDate: '2019-08-23',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '34,45',
        payer: 'Miha',
        payDate: '2019-09-23',
        description: '',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '37,40',
        payer: 'Nataša',
        payDate: '2021-09-23',
        description: 'Lora - Cardiovet',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '20,45',
        payer: 'Miha',
        payDate: '2021-11-23',
        description: '',
        shared: true,
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: '60,00',
        payer: 'Nataša',
        payDate: '2019-12-23',
        description: 'Darilo MH escaperoom',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '40,00',
        payer: 'Nataša',
        payDate: '2020-12-23',
        description: 'MED',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '32,13',
        payer: 'Nataša',
        payDate: '2020-01-24',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '15,00',
        payer: 'Nataša',
        payDate: '2021-03-24',
        description: 'Jajca in tržnica',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '9,00',
        payer: 'Nataša',
        payDate: '2021-03-24',
        description: 'Lora - tablete',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '37,06',
        payer: 'Miha',
        payDate: '2022-03-24',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '16,45',
        payer: 'Miha',
        payDate: '2019-09-24',
        description: '',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Pnevmatike',
        cost: '207,50',
        payer: 'Nataša',
        payDate: '2019-10-24',
        description: 'BMW - gume',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Pnevmatike',
        cost: '207,50',
        payer: 'Miha',
        payDate: '2019-10-24',
        description: 'BMW - gume',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '13,22',
        payer: 'Nataša',
        payDate: '2021-11-24',
        description: 'RIBA',
        shared: true,
    },
    {
        category: 'Zabava',
        subCategory: 'Igrice',
        cost: '36,11',
        payer: 'Nataša',
        payDate: '2021-11-24',
        description: 'TASTER - PS4',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '18,00',
        payer: 'Miha',
        payDate: '2021-11-24',
        description: 'BOUL',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '25,00',
        payer: 'Miha',
        payDate: '2022-01-25',
        description: 'Trgovina - živila',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Vzdrževanje',
        cost: '515,00',
        payer: 'Nataša',
        payDate: '2020-02-25',
        description: 'BMW - menjava 4x amortizerji',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '89,50',
        payer: 'Nataša',
        payDate: '2022-03-25',
        description: 'Lora - pregled in zdravila',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '51,60',
        payer: 'Miha',
        payDate: '2022-04-25',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Lekarna',
        cost: '63,00',
        payer: 'Nataša',
        payDate: '2022-05-25',
        description: 'Dodatki - prehrana Tablete za seme :)',
        shared: true,
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: '118,25',
        payer: 'Miha',
        payDate: '2021-09-25',
        description: 'Miha RD',
        shared: true,
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: '20,00',
        payer: 'Miha',
        payDate: '2019-12-25',
        description: 'Darilo otroci Slatna',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '39,24',
        payer: 'Miha',
        payDate: '2021-01-26',
        description: '',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '43,00',
        payer: 'Miha',
        payDate: '2022-05-26',
        description: 'Lora - zdravila',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '48,27',
        payer: 'Miha',
        payDate: '2020-03-27',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '2,50',
        payer: 'Nataša',
        payDate: '2020-05-27',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '57,58',
        payer: 'Miha',
        payDate: '2022-05-27',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '23,24',
        payer: 'Miha',
        payDate: '2022-08-27',
        description: 'Rezervni sklad GARAŽA (5/6/7/8[22])',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '44,87',
        payer: 'Miha',
        payDate: '2019-09-27',
        description: '',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '59,80',
        payer: 'Nataša',
        payDate: '2021-10-27',
        description: 'Lora - Dialix',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '10,00',
        payer: 'Nataša',
        payDate: '2020-11-27',
        description: 'Jajca in skuta',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '44,46',
        payer: 'Miha',
        payDate: '2019-12-27',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '31,00',
        payer: 'Nataša',
        payDate: '2019-12-27',
        description: 'Notar za Nives',
        shared: true,
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: '16,00',
        payer: 'Miha',
        payDate: '2019-12-27',
        description: 'Tortice za Anjin rojstni dan',
        shared: true,
    },
    {
        category: 'Clio',
        subCategory: 'Gorivo',
        cost: '36,00',
        payer: 'Nataša',
        payDate: '2020-12-27',
        description: 'Bencin - Clio',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '53,44',
        payer: 'Miha',
        payDate: '2020-01-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '46,29',
        payer: 'Miha',
        payDate: '2020-01-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '60,73',
        payer: 'Miha',
        payDate: '2022-01-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '53,57',
        payer: 'Miha',
        payDate: '2020-02-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '69,08',
        payer: 'Miha',
        payDate: '2021-02-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '54,86',
        payer: 'Nataša',
        payDate: '2022-02-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '46,94',
        payer: 'Miha',
        payDate: '2021-03-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '45,74',
        payer: 'Miha',
        payDate: '2022-03-28',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '32,42',
        payer: 'Nataša',
        payDate: '2022-03-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '40,32',
        payer: 'Miha',
        payDate: '2020-04-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '23,24',
        payer: 'Miha',
        payDate: '2021-04-28',
        description: 'Rezervni sklad GARAŽA (1/2/3/4[21])',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '44,89',
        payer: 'Miha',
        payDate: '2021-04-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '23,24',
        payer: 'Miha',
        payDate: '2022-04-28',
        description: 'Rezervni sklad GARAŽA (1/2/3/4[22])',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '50,66',
        payer: 'Miha',
        payDate: '2020-05-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '62,33',
        payer: 'Miha',
        payDate: '2021-05-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '42,28',
        payer: 'Miha',
        payDate: '2021-06-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '42,18',
        payer: 'Miha',
        payDate: '2020-07-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '42,33',
        payer: 'Miha',
        payDate: '2021-07-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '38,79',
        payer: 'Miha',
        payDate: '2020-08-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '23,24',
        payer: 'Miha',
        payDate: '2021-08-28',
        description: 'Rezervni sklad GARAŽA (5/6/7/8[21])',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '42,75',
        payer: 'Miha',
        payDate: '2021-08-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '45,49',
        payer: 'Miha',
        payDate: '2020-09-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '42,41',
        payer: 'Miha',
        payDate: '2021-09-28',
        description: '',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '79,88',
        payer: 'Nataša',
        payDate: '2021-09-28',
        description: 'Lora - hrana',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '38,75',
        payer: 'Miha',
        payDate: '2019-10-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '66,08',
        payer: 'Miha',
        payDate: '2020-10-28',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '5,00',
        payer: 'Nataša',
        payDate: '2020-10-28',
        description: 'Jajca',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '47,58',
        payer: 'Miha',
        payDate: '2021-10-28',
        description: '',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '45,14',
        payer: 'Nataša',
        payDate: '2021-10-28',
        description: 'Lora - Klobase',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '68,00',
        payer: 'Miha',
        payDate: '2019-11-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '42,75',
        payer: 'Miha',
        payDate: '2021-11-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '56,14',
        payer: 'Miha',
        payDate: '2020-12-28',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '23,24',
        payer: 'Miha',
        payDate: '2021-12-28',
        description: 'Rezervni sklad GARAŽA (9/10/11/12[21])',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '69,99',
        payer: 'Miha',
        payDate: '2021-12-28',
        description: '',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '19,30',
        payer: 'Nataša',
        payDate: '2021-12-28',
        description: 'Lora - zdravila EPATO',
        shared: true,
    },
    {
        category: 'Hobi',
        subCategory: 'Plezanje',
        cost: '24,00',
        payer: 'Nataša',
        payDate: '2021-03-29',
        description: 'Plezanje',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '55,83',
        payer: 'Nataša',
        payDate: '2022-04-29',
        description: 'BMW - Nafta',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '38,17',
        payer: 'Miha',
        payDate: '2020-06-29',
        description: '',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Vzdrževanje',
        cost: '50,00',
        payer: 'Nataša',
        payDate: '2020-06-29',
        description:
            'BMW - popravilo levega ABS senzorja(podstavitev), dopolnil nivo olja',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '16,69',
        payer: 'Miha',
        payDate: '2021-09-29',
        description: 'eHrana',
        shared: true,
    },
    {
        category: 'Zabava',
        subCategory: 'Knjige',
        cost: '25,00',
        payer: 'Nataša',
        payDate: '2020-12-29',
        description: 'Knjiga - Štajerski Argo',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '20,00',
        payer: 'Nataša',
        payDate: '2022-01-30',
        description: 'Hrana in testi',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '61,00',
        payer: 'Nataša',
        payDate: '2021-03-30',
        description: 'Lora - pregled in zdravila',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '76,66',
        payer: 'Miha',
        payDate: '2022-03-30',
        description: 'BMW - GORIVO',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '17,00',
        payer: 'Miha',
        payDate: '2022-03-30',
        description: 'take out',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '9,50',
        payer: 'Nataša',
        payDate: '2022-04-30',
        description: 'špar',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '58,58',
        payer: 'Nataša',
        payDate: '2022-04-30',
        description: 'Hofer',
        shared: true,
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '74,00',
        payer: 'Miha',
        payDate: '2022-05-30',
        description: 'BMW - Gorivo',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '45,00',
        payer: 'Nataša',
        payDate: '2020-09-30',
        description: 'IKEA',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '47,10',
        payer: 'Nataša',
        payDate: '2021-09-30',
        description: 'Lora - Zdravila',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '14,30',
        payer: 'Nataša',
        payDate: '2021-09-30',
        description: 'SPAR',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '69,82',
        payer: 'Miha',
        payDate: '2020-11-30',
        description: '',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '88,00',
        payer: 'Nataša',
        payDate: '2020-12-30',
        description: 'Lora - hrana',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Mercator',
        cost: '9,96',
        payer: 'Nataša',
        payDate: '2021-12-30',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '50,16',
        payer: 'Nataša',
        payDate: '2021-12-30',
        description: '',
        shared: true,
    },
    {
        category: 'Clio',
        subCategory: 'Gorivo',
        cost: '51,71',
        payer: 'Nataša',
        payDate: '2021-12-30',
        description: 'Clio - tank',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Mercator',
        cost: '20,00',
        payer: 'Miha',
        payDate: '2021-05-06',
        description: 'Mercator darila Slatna',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Mercator',
        cost: '49,49',
        payer: 'Miha',
        payDate: '2021-05-07',
        description: 'Mercator čokolade in kosilo',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '22,68',
        payer: 'Nataša',
        payDate: '2021-05-08',
        description: '',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '59,02',
        payer: 'Miha',
        payDate: '2021-05-08',
        description: 'hrana Spar brunch',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '48,92',
        payer: 'Miha',
        payDate: '2021-05-08',
        description: 'Lora - veterinar Lj',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '18,82',
        payer: 'Miha',
        payDate: '2021-05-08',
        description: 'Lora - veterinar Logatec',
        shared: true,
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '14,00',
        payer: 'Nataša',
        payDate: '2021-05-09',
        description: 'Lora - Lanitop',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '20,00',
        payer: 'Nataša',
        payDate: '2022-06-16',
        description: 'IKEA',
        shared: true,
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '13,00',
        payer: 'Nataša',
        payDate: '2022-06-18',
        description: '',
        shared: true,
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '47,19',
        payer: 'Miha',
        payDate: '2022-06-28',
        description: '',
        shared: true,
    },
]
