module.exports = [
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: 50,
        payer: 'Miha',
        payDate: '2021-2-1',
        description: 'BMW - gorivo',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Lekarna',
        cost: 44,
        payer: 'Nataša',
        payDate: '2021-2-1',
        description: 'Zdravila in krema za vimene',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: 91,
        payer: 'Nataša',
        payDate: '2020-4-1',
        description: 'Hrana med Karanteno',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 10,
        payer: 'Nataša',
        payDate: '2021-4-1',
        description: 'Jajca in hrana',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: 12,
        payer: 'Miha',
        payDate: '2022-6-1',
        description: 'Kosilo Bohinj-�trudl',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: 17.8,
        payer: 'Miha',
        payDate: '2022-6-1',
        description: 'Maharaja',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: 18,
        payer: 'Miha',
        payDate: '2021-7-1',
        description: 'Mahara�a',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: 240,
        payer: 'Nataša',
        payDate: '2021-7-1',
        description: 'Razvla�evalnik Qlima',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: 102.9,
        payer: 'Nataša',
        payDate: '2021-9-1',
        description: 'nordic nest',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: 9.57,
        payer: 'Miha',
        payDate: '2021-10-1',
        description: 'Spar',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 8,
        payer: 'Nataša',
        payDate: '2020-12-1',
        description: 'jogurt, kruh',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: 70,
        payer: 'Miha',
        payDate: '2022-1-2',
        description: 'BMW - Gorivo',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: 30,
        payer: 'Miha',
        payDate: '2021-4-2',
        description: 'SPAR',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: 36,
        payer: 'Nataša',
        payDate: '2022-4-2',
        description: 'Harvey Norman',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '20,8',
        payer: 'Nataša',
        payDate: '2022-6-2',
        description: 'Hrana Bohinj-�trudl',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: 55,
        payer: 'Nataša',
        payDate: '2020-7-2',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '128,67',
        payer: 'Miha',
        payDate: '2021-7-2',
        description:
            'Miele - servis pomivalni (NTC, Nepovratni ventil, tesnilo za lesk))',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: 250,
        payer: 'Miha',
        payDate: '2021-7-2',
        description: 'Slikce  - okvirji',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: 23,
        payer: 'Miha',
        payDate: '2021-7-2',
        description: 'Dobra Vila Pizza',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: 35,
        payer: 'Miha',
        payDate: '2021-8-2',
        description: 'Lora - dihtnge',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Moda',
        cost: 37,
        payer: 'Miha',
        payDate: '2021-8-2',
        description: 'Lora - rjuhe',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 17,
        payer: 'Nataša',
        payDate: '2021-8-2',
        description: 'Skute',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '2,3',
        payer: 'Nataša',
        payDate: '2021-10-2',
        description: 'DM',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 2,
        payer: 'Nataša',
        payDate: '2020-12-2',
        description: 'jajca',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '34,36',
        payer: 'Nataša',
        payDate: '2021-12-2',
        description: 'Spar',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '88,16',
        payer: 'Nataša',
        payDate: '2022-1-3',
        description: 'Lora - Vet',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '47,03',
        payer: 'Nataša',
        payDate: '2022-1-3',
        description: 'Lora - Hrana',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: 20,
        payer: 'Nataša',
        payDate: '2022-2-3',
        description: 'Hrana',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: 70,
        payer: 'Nataša',
        payDate: '2021-3-3',
        description: 'Lora - zdravila',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '115,63',
        payer: 'Miha',
        payDate: '2022-3-3',
        description: 'Panda Mini Advanced Fuzzy Logic Ceramic Rice Cooker',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '96,48',
        payer: 'Miha',
        payDate: '2022-5-3',
        description: 'Lora - vetmedin',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '13,28',
        payer: 'Nataša',
        payDate: '2022-5-3',
        description: 'Lora - vetmedin',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 13,
        payer: 'Nataša',
        payDate: '2020-6-3',
        description: 'Jajca in skuta',
        shared: 'TRUE',
    },
    {
        category: 'Zabava',
        subCategory: 'Dopust',
        cost: '46,4',
        payer: 'Miha',
        payDate: '2022-6-3',
        description: 'Hotel Bohinj',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: 30,
        payer: 'Miha',
        payDate: '2022-6-3',
        description: 'Kava in �okolada',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '17,4',
        payer: 'Nataša',
        payDate: '2021-7-3',
        description: 'Skute in zelenjava',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: 47,
        payer: 'Nataša',
        payDate: '2021-7-3',
        description: 'Mol - BMW tank',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 37,
        payer: 'Nataša',
        payDate: '2019-10-3',
        description: 'Med',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '10,28',
        payer: 'Nataša',
        payDate: '2021-11-3',
        description: 'DM',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '179,11',
        payer: 'Miha',
        payDate: '2022-1-4',
        description: 'Lora - Pregled',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Pnevmatike',
        cost: '333,46',
        payer: 'Nataša',
        payDate: '2021-3-4',
        description: 'BMW - Letne gume DOT 4920',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 5,
        payer: 'Nataša',
        payDate: '2021-3-4',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '14,69',
        payer: 'Nataša',
        payDate: '2022-4-4',
        description: 'Spar',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '10,5',
        payer: 'Nataša',
        payDate: '2021-5-4',
        description: 'Lora - Vetmedin',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '48,84',
        payer: 'Nataša',
        payDate: '2021-5-4',
        description: 'Lora - Hrana',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: 22,
        payer: 'Nataša',
        payDate: '2021-5-4',
        description: 'Lora - Zdravila',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '42,79',
        payer: 'Nataša',
        payDate: '2021-5-4',
        description: 'BMW - Tank',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 5,
        payer: 'Nataša',
        payDate: '2022-5-4',
        description: 'Jajca in jogurti',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Mercator',
        cost: 28,
        payer: 'Nataša',
        payDate: '2020-6-4',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 5,
        payer: 'Nataša',
        payDate: '2020-6-4',
        description: 'Jagode',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '23,5',
        payer: 'Nataša',
        payDate: '2019-11-4',
        description: 'IKEA',
        shared: 'TRUE',
    },
    {
        category: 'Hobi',
        subCategory: 'Kolesarstvo',
        cost: 650,
        payer: 'Miha',
        payDate: '2019-11-4',
        description: 'Trena�er ELITE DIRETO X',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '2,5',
        payer: 'Nataša',
        payDate: '2020-11-4',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Zabava',
        subCategory: 'Dopust',
        cost: '175,1',
        payer: 'Nataša',
        payDate: '2021-11-4',
        description: 'Rimske Toplice',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '10,7',
        payer: 'Nataša',
        payDate: '2021-11-4',
        description: 'PICA',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '19,98',
        payer: 'Nataša',
        payDate: '2021-12-4',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '8,32',
        payer: 'Miha',
        payDate: '2021-12-4',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '78,84',
        payer: 'Miha',
        payDate: '2021-12-4',
        description: 'IKEA',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: 80,
        payer: 'Nataša',
        payDate: '2021-1-5',
        description: 'Trgovina - Hofer',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '34,04',
        payer: 'Miha',
        payDate: '2022-4-5',
        description: 'BMW - GORIVO',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '6,2',
        payer: 'Nataša',
        payDate: '2020-5-5',
        description: 'Skuta',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '89,86',
        payer: 'Miha',
        payDate: '2021-5-5',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '61,82',
        payer: 'Miha',
        payDate: '2021-5-5',
        description: 'Lora - Pregled krvi',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '9,66',
        payer: 'Nataša',
        payDate: '2021-8-5',
        description: 'DM',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: 10,
        payer: 'Nataša',
        payDate: '2019-11-5',
        description: 'Pra�ek',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 3,
        payer: 'Miha',
        payDate: '2020-11-5',
        description: 'Kis',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '57,43',
        payer: 'Miha',
        payDate: '2021-12-5',
        description: 'BAUHAUS',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tuš',
        cost: '56,67',
        payer: 'Miha',
        payDate: '2021-2-6',
        description: 'Tu�, fasnga',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 10,
        payer: 'Nataša',
        payDate: '2021-2-6',
        description: 'jogurti in skute',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Zavarovanje',
        cost: '410,65',
        payer: 'Nataša',
        payDate: '2020-5-6',
        description: 'BMW - Zavarovanje',
        shared: 'TRUE',
    },
    {
        category: 'Clio',
        subCategory: 'Gorivo',
        cost: '45,73',
        payer: 'Nataša',
        payDate: '2021-5-6',
        description: 'Clio - Gorivo',
        shared: 'TRUE',
    },
    {
        category: 'Darila',
        subCategory: 'Prijatelji',
        cost: 50,
        payer: 'Nataša',
        payDate: '2022-6-6',
        description: 'Darilo - Nel',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Lekarna',
        cost: '3,2',
        payer: 'Nataša',
        payDate: '2021-7-6',
        description: 'Lekarna',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '33,78',
        payer: 'Nataša',
        payDate: '2021-7-6',
        description: 'SPAR',
        shared: 'TRUE',
    },
    {
        category: 'Clio',
        subCategory: 'Zavarovanje',
        cost: '169,12',
        payer: 'Miha',
        payDate: '2019-11-6',
        description: 'Zavarovanje Clio',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '87,94',
        payer: 'Nataša',
        payDate: '2021-11-6',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '16,94',
        payer: 'Nataša',
        payDate: '2021-11-6',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Mercator',
        cost: '26,27',
        payer: 'Miha',
        payDate: '2021-12-6',
        description: 'MERCATOR',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '147,1',
        payer: 'Miha',
        payDate: '2021-12-6',
        description: 'Lora - zdravila',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: 19,
        payer: 'Nataša',
        payDate: '2022-1-7',
        description: 'Lora - zdravila',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: 83,
        payer: 'Miha',
        payDate: '2020-3-7',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: 49,
        payer: 'Nataša',
        payDate: '2021-3-7',
        description: 'SPAR, HOFER, DM',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: 104,
        payer: 'Miha',
        payDate: '2022-3-7',
        description: 'IKEA - Ko�are',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: 34,
        payer: 'Nataša',
        payDate: '2022-3-7',
        description: 'Lora - zdravila',
        shared: 'TRUE',
    },
    {
        category: 'Clio',
        subCategory: 'Gorivo',
        cost: 54,
        payer: 'Nataša',
        payDate: '2022-3-7',
        description: 'Clio - benz',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 8,
        payer: 'Nataša',
        payDate: '2022-3-7',
        description: 'Tržnica',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 10,
        payer: 'Nataša',
        payDate: '2022-4-7',
        description: 'Tržnica',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: 31,
        payer: 'Nataša',
        payDate: '2022-5-7',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '14,04',
        payer: 'Nataša',
        payDate: '2022-5-7',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Moda',
        cost: 50,
        payer: 'Miha',
        payDate: '2022-5-7',
        description: 'Lora - frizer',
        shared: 'TRUE',
    },
    {
        category: 'Darila',
        subCategory: 'Prijatelji',
        cost: 60,
        payer: 'Miha',
        payDate: '2022-5-7',
        description: 'Darilo Mato(Escape room bon)',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '2,5',
        payer: 'Nataša',
        payDate: '2022-6-7',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: 150,
        payer: 'Nataša',
        payDate: '2022-6-7',
        description: 'Lora - pregled in zdravila',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '24,14',
        payer: 'Nataša',
        payDate: '2021-8-7',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '14,66',
        payer: 'Nataša',
        payDate: '2021-8-7',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '8,06',
        payer: 'Nataša',
        payDate: '2021-8-7',
        description: 'SPAR',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 5,
        payer: 'Nataša',
        payDate: '2020-10-7',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '68,18',
        payer: 'Miha',
        payDate: '2021-10-7',
        description: 'BMW - Mol',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '30,34',
        payer: 'Miha',
        payDate: '2021-10-7',
        description: 'Hofer',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: 21,
        payer: 'Miha',
        payDate: '2021-10-7',
        description: 'Hrana',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 15,
        payer: 'Nataša',
        payDate: '2021-10-7',
        description: 'Jajca in med',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 10,
        payer: 'Nataša',
        payDate: '2020-11-7',
        description: 'Jogurti',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: 150,
        payer: 'Nataša',
        payDate: '2020-12-7',
        description: 'Lora - pregled, zdravila in hrana (vnetje �elodca)',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '53,33',
        payer: 'Miha',
        payDate: '2020-12-7',
        description: 'BMW - gorivo',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: 13,
        payer: 'Nataša',
        payDate: '2021-1-8',
        description: 'Trgovina',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '49,34',
        payer: 'Miha',
        payDate: '2022-1-8',
        description: 'Spar',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '97,4',
        payer: 'Nataša',
        payDate: '2022-3-8',
        description: 'Lora - pregled',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '95,23',
        payer: 'Nataša',
        payDate: '2022-6-8',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: 40,
        payer: 'Nataša',
        payDate: '2021-9-8',
        description: 'Lora - Hrana',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '12,89',
        payer: 'Miha',
        payDate: '2021-9-8',
        description: 'Roomba - Filtri',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 20,
        payer: 'Nataša',
        payDate: '2021-1-9',
        description: 'Tržnica',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Moda',
        cost: 50,
        payer: 'Miha',
        payDate: '2021-1-9',
        description: 'Lora - Frizerka Tina',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '42,91',
        payer: 'Miha',
        payDate: '2021-2-9',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 10,
        payer: 'Nataša',
        payDate: '2020-4-9',
        description: 'Jajca in skuta',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: 470,
        payer: 'Miha',
        payDate: '2022-5-9',
        description: 'Omara - predelava predalnikov',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '43,84',
        payer: 'Miha',
        payDate: '2022-6-9',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Mercator',
        cost: '8,2',
        payer: 'Nataša',
        payDate: '2020-7-9',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 5,
        payer: 'Nataša',
        payDate: '2020-7-9',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 25,
        payer: 'Nataša',
        payDate: '2020-7-9',
        description: 'FlapJack',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '18,87',
        payer: 'Nataša',
        payDate: '2021-7-9',
        description: 'HOFER',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '22,14',
        payer: 'Miha',
        payDate: '2021-9-9',
        description: 'BAUHAUS - orodje',
        shared: 'TRUE',
    },
    {
        category: 'Clio',
        subCategory: 'Gorivo',
        cost: '58,36',
        payer: 'Nataša',
        payDate: '2021-9-9',
        description: 'Mol',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '24,45',
        payer: 'Miha',
        payDate: '2021-9-9',
        description: 'DM',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '2,5',
        payer: 'Nataša',
        payDate: '2021-10-9',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Clio',
        subCategory: 'Registracija',
        cost: '107,48',
        payer: 'Nataša',
        payDate: '2019-11-9',
        description: 'Registracija Clio',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: 113,
        payer: 'Nataša',
        payDate: '2020-11-9',
        description: 'Vzglavniki',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Zavarovanje',
        cost: '465,74',
        payer: 'Nataša',
        payDate: '2021-11-9',
        description: 'BMW - Zavarovanje',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '29,7',
        payer: 'Nataša',
        payDate: '2022-1-10',
        description: 'Lora - veterinar',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: 30,
        payer: 'Nataša',
        payDate: '2022-1-10',
        description: 'Lora - zdravila',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Vzdrževanje',
        cost: 200,
        payer: 'Nataša',
        payDate: '2021-2-10',
        description: 'BMW - Servis, mali',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 10,
        payer: 'Miha',
        payDate: '2022-4-10',
        description: 'Tržnica',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '12,96',
        payer: 'Miha',
        payDate: '2019-9-10',
        description: 'Interkalarne obresti kredita',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: 34,
        payer: 'Nataša',
        payDate: '2019-10-10',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Clio',
        subCategory: 'Zavarovanje',
        cost: '231,65',
        payer: 'Nataša',
        payDate: '2021-11-10',
        description: 'Clio - Zavarovanje',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '2,5',
        payer: 'Nataša',
        payDate: '2021-11-10',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '60,61',
        payer: 'Nataša',
        payDate: '2021-1-11',
        description: 'Lora - cepljenje',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Vzdrževanje',
        cost: 209,
        payer: 'Miha',
        payDate: '2022-2-11',
        description: 'BMW - Servis(olje in filtri, AirBag)',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: 170,
        payer: 'Nataša',
        payDate: '2021-4-11',
        description: 'Lora - Vet, sr�ek :/',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '23,5',
        payer: 'Nataša',
        payDate: '2020-5-11',
        description: 'Jagode, skuta, jajca',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '54,8',
        payer: 'Nataša',
        payDate: '2021-5-11',
        description: 'Pizza - Trapa (Joc, Nel, Jaz)',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '42,5',
        payer: 'Miha',
        payDate: '2021-6-11',
        description: 'Dimnikar 2021',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 8,
        payer: 'Nataša',
        payDate: '2021-7-11',
        description: 'Zelenjava',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '58,36',
        payer: 'Nataša',
        payDate: '2021-9-11',
        description: 'BMW - Gorivo',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '39,94',
        payer: 'Nataša',
        payDate: '2021-9-11',
        description: 'Lora - Hrana',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Moda',
        cost: 50,
        payer: 'Nataša',
        payDate: '2021-11-11',
        description: 'Lora - Frizer',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 51,
        payer: 'Nataša',
        payDate: '2021-11-11',
        description: 'Med',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 5,
        payer: 'Nataša',
        payDate: '2021-12-11',
        description: 'Tržnica',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 30,
        payer: 'Miha',
        payDate: '2021-12-11',
        description: 'Tržnica',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Moda',
        cost: 80,
        payer: 'Nataša',
        payDate: '2021-1-12',
        description: 'Lora - oprsnica',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '12,66',
        payer: 'Miha',
        payDate: '2021-2-12',
        description: 'Gumbi z vijaki - �aluzije',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: 37,
        payer: 'Nataša',
        payDate: '2021-2-12',
        description: 'Lora - Zdravila',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '89,48',
        payer: 'Nataša',
        payDate: '2021-4-12',
        description: 'Lora - Hrana',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 1,
        payer: 'Nataša',
        payDate: '2021-4-12',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: 20,
        payer: 'Nataša',
        payDate: '2021-4-12',
        description: 'Lora - zdravila',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '100,4',
        payer: 'Nataša',
        payDate: '2022-4-12',
        description: 'Lora - Veterinar in zdravila',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Pnevmatike',
        cost: 64,
        payer: 'Nataša',
        payDate: '2022-5-12',
        description: 'BMW - Menjava gum 50 - 14(hramba)',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Zavarovanje',
        cost: '239,27',
        payer: 'Nataša',
        payDate: '2022-5-12',
        description:
            'BMW - zavarobvanje, pla�ilo razlike za uskladitev datumov zav. in reg.',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 13,
        payer: 'Miha',
        payDate: '2020-12-12',
        description: 'Skute in mle�ni izdelki',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'E.Leclerc',
        cost: '16,25',
        payer: 'Miha',
        payDate: '2021-1-13',
        description: 'Razvajanje iz E.Leclerc',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '64,75',
        payer: 'Miha',
        payDate: '2020-3-13',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: '2,8',
        payer: 'Nataša',
        payDate: '2021-5-13',
        description: 'Po�tnina za darilo, Slatna',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '43,7',
        payer: 'Miha',
        payDate: '2022-5-13',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 22,
        payer: 'Nataša',
        payDate: '2020-6-13',
        description: 'Skuta',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 5,
        payer: 'Nataša',
        payDate: '2020-8-13',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '45,93',
        payer: 'Miha',
        payDate: '2021-8-13',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '34,45',
        payer: 'Miha',
        payDate: '2019-9-13',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '51,35',
        payer: 'Miha',
        payDate: '2020-11-13',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '33,71',
        payer: 'Miha',
        payDate: '2019-12-13',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '44,66',
        payer: 'Miha',
        payDate: '2020-2-14',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '49,27',
        payer: 'Miha',
        payDate: '2021-5-14',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '20,76',
        payer: 'Miha',
        payDate: '2022-5-14',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: 44,
        payer: 'Miha',
        payDate: '2022-6-14',
        description: 'Lora - zdravila',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '47,64',
        payer: 'Miha',
        payDate: '2020-8-14',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '45,33',
        payer: 'Nataša',
        payDate: '2021-9-14',
        description: 'SPAR',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '34,45',
        payer: 'Miha',
        payDate: '2019-10-14',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: 15,
        payer: 'Nataša',
        payDate: '2021-10-14',
        description: 'Torticeee',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '33,71',
        payer: 'Miha',
        payDate: '2019-11-14',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Clio',
        subCategory: 'Vzdrževanje',
        cost: 80,
        payer: 'Miha',
        payDate: '2020-11-14',
        description: 'Mali servis Clio, lu�i, olje, teko�ine, man�ete',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '28,5',
        payer: 'Miha',
        payDate: '2021-11-14',
        description: 'Lora - lanitop',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '49,49',
        payer: 'Miha',
        payDate: '2020-12-14',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '49,49',
        payer: 'Miha',
        payDate: '2021-1-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '49,77',
        payer: 'Miha',
        payDate: '2021-2-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '46,25',
        payer: 'Miha',
        payDate: '2022-2-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '51,01',
        payer: 'Miha',
        payDate: '2021-3-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 20,
        payer: 'Nataša',
        payDate: '2021-3-15',
        description: 'Tržnica',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '33,96',
        payer: 'Miha',
        payDate: '2022-3-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '48,31',
        payer: 'Miha',
        payDate: '2020-4-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 4,
        payer: 'Miha',
        payDate: '2020-4-15',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '49,42',
        payer: 'Miha',
        payDate: '2021-4-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '48,31',
        payer: 'Miha',
        payDate: '2020-5-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 52,
        payer: 'Miha',
        payDate: '2020-5-15',
        description: 'Meso(20), Suho sadje(32)',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '47,64',
        payer: 'Miha',
        payDate: '2020-6-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Zabava',
        subCategory: 'Dopust',
        cost: 50,
        payer: 'Nataša',
        payDate: '2020-6-15',
        description: 'Menjava kun',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '46,83',
        payer: 'Miha',
        payDate: '2021-6-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '48,2',
        payer: 'Miha',
        payDate: '2022-6-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '47,64',
        payer: 'Miha',
        payDate: '2020-7-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '46,22',
        payer: 'Miha',
        payDate: '2021-7-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '55,06',
        payer: 'Miha',
        payDate: '2020-9-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '47,64',
        payer: 'Miha',
        payDate: '2020-10-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 20,
        payer: 'Miha',
        payDate: '2020-11-15',
        description: 'Bu�no olje',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '5,1',
        payer: 'Nataša',
        payDate: '2020-11-15',
        description: 'Skute, kruh, jogurt',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '46,59',
        payer: 'Miha',
        payDate: '2021-11-15',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 10,
        payer: 'Nataša',
        payDate: '2021-11-15',
        description: 'Tržnica',
        shared: 'TRUE',
    },
    {
        category: 'Hobi',
        subCategory: 'Plezanje',
        cost: 275,
        payer: 'Miha',
        payDate: '2020-1-16',
        description: 'Plezanje Mi�ko, December, januar do 14.februarja',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 10,
        payer: 'Nataša',
        payDate: '2022-2-16',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '6,2',
        payer: 'Nataša',
        payDate: '2020-4-16',
        description: 'Skuta',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '11,3',
        payer: 'Nataša',
        payDate: '2021-5-16',
        description: 'Lora - Edemid',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Registracija',
        cost: 199,
        payer: 'Miha',
        payDate: '2022-5-16',
        description: 'BMW - Tehni�ni in registracija',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '2,5',
        payer: 'Nataša',
        payDate: '2021-6-16',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Lekarna',
        cost: '8,2',
        payer: 'Nataša',
        payDate: '2021-6-16',
        description: 'Krema za sun�anje',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 10,
        payer: 'Nataša',
        payDate: '2021-6-16',
        description: 'MED',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '42,37',
        payer: 'Miha',
        payDate: '2021-9-16',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Clio',
        subCategory: 'Zavarovanje',
        cost: '127,98',
        payer: 'Nataša',
        payDate: '2020-11-16',
        description: 'Zavarovanje Clio',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '79,88',
        payer: 'Nataša',
        payDate: '2021-11-16',
        description: 'Lora - klobase',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: 19,
        payer: 'Miha',
        payDate: '2021-11-16',
        description: 'Kosilo',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Registracija',
        cost: '83,42',
        payer: 'Nataša',
        payDate: '2022-1-17',
        description: 'BMW - Registracija (poziv pred odjavo iz prometa)',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '95,4',
        payer: 'Nataša',
        payDate: '2022-2-17',
        description: 'ARTLES - dva stola(mala)',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-5-17',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Registracija',
        cost: 120,
        payer: 'Nataša',
        payDate: '2021-5-17',
        description: 'BMW - registracija in tehni�ni pregled',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: 50,
        payer: 'Nataša',
        payDate: '2022-5-17',
        description: 'Lora - hrana',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Vzdrževanje',
        cost: 10,
        payer: 'Nataša',
        payDate: '2020-6-17',
        description: 'BMW - pregled zadnjih enkoderjev [ABS]',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '47,03',
        payer: 'Miha',
        payDate: '2021-9-17',
        description: 'BMW - gorivo',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '41,28',
        payer: 'Miha',
        payDate: '2021-9-17',
        description: 'SPAR - Hrana',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '37,05',
        payer: 'Nataša',
        payDate: '2021-5-17',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '31,45',
        payer: 'Nataša',
        payDate: '2020-1-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2020-1-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '47,54',
        payer: 'Nataša',
        payDate: '2021-1-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2022-1-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2022-1-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '47,96',
        payer: 'Nataša',
        payDate: '2022-1-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '41,65',
        payer: 'Miha',
        payDate: '2022-1-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2020-2-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '34,07',
        payer: 'Nataša',
        payDate: '2020-2-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2021-2-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '45,4',
        payer: 'Nataša',
        payDate: '2021-2-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2022-2-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '48,57',
        payer: 'Nataša',
        payDate: '2022-2-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2022-2-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 2,
        payer: 'Nataša',
        payDate: '2022-2-18',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2020-3-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '32,1',
        payer: 'Nataša',
        payDate: '2020-3-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2021-3-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '39,25',
        payer: 'Nataša',
        payDate: '2021-3-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 32,
        payer: 'Miha',
        payDate: '2021-3-18',
        description: 'Kis in bu�no olje.',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2022-3-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2022-3-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '17,54',
        payer: 'Nataša',
        payDate: '2022-3-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2020-4-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2021-4-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2022-4-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '25,23',
        payer: 'Nataša',
        payDate: '2020-5-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2020-5-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2021-5-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2022-5-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2022-5-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '17,53',
        payer: 'Nataša',
        payDate: '2022-5-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2020-6-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '21,06',
        payer: 'Nataša',
        payDate: '2020-6-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '42,5',
        payer: 'Nataša',
        payDate: '2020-6-18',
        description: 'Dimnikar',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-6-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '36,19',
        payer: 'Nataša',
        payDate: '2021-6-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2021-6-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '29,85',
        payer: 'Miha',
        payDate: '2021-6-18',
        description: 'Lars&Sven',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2022-6-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2021-7-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '3030-7-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2020-8-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '35,05',
        payer: 'Nataša',
        payDate: '2020-8-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '203,99',
        payer: 'Nataša',
        payDate: '2020-8-18',
        description: 'Cenitev stanovanja',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '53,6',
        payer: 'Miha',
        payDate: '2020-8-18',
        description: 'Servis pe�i - letni pregled',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: 10,
        payer: 'Nataša',
        payDate: '2020-8-18',
        description: 'Vinkulacija',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '204,01',
        payer: 'Nataša',
        payDate: '2020-8-18',
        description: 'Zavarovanje stanovanja',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2021-8-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '38,17',
        payer: 'Nataša',
        payDate: '2021-8-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '204,01',
        payer: 'Nataša',
        payDate: '2021-8-18',
        description: 'Zavarovanje stanovanja',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '34,87',
        payer: 'Nataša',
        payDate: '2020-9-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2020-9-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2021-9-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '31,32',
        payer: 'Nataša',
        payDate: '2021-9-18',
        description: 'Ponev',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '27,78',
        payer: 'Nataša',
        payDate: '2019-10-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 30,
        payer: 'Nataša',
        payDate: '2019-10-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2020-10-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-10-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2021-10-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '45,08',
        payer: 'Miha',
        payDate: '2021-10-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '36,12',
        payer: 'Nataša',
        payDate: '2021-10-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 30,
        payer: 'Nataša',
        payDate: '2019-11-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '29,69',
        payer: 'Nataša',
        payDate: '2019-11-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Vzdrževanje',
        cost: 128,
        payer: 'Miha',
        payDate: '2019-11-18',
        description: 'BMW - servis - olje, filtri',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2020-11-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '42,53',
        payer: 'Nataša',
        payDate: '2020-11-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-11-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2021-11-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '38,92',
        payer: 'Nataša',
        payDate: '2021-11-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 30,
        payer: 'Nataša',
        payDate: '2019-12-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '32,83',
        payer: 'Nataša',
        payDate: '2019-12-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '45,19',
        payer: 'Nataša',
        payDate: '2020-12-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2020-12-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: 35,
        payer: 'Nataša',
        payDate: '2021-12-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '45,18',
        payer: 'Miha',
        payDate: '2021-12-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '40,82',
        payer: 'Nataša',
        payDate: '2021-4-19',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '19,63',
        payer: 'Nataša',
        payDate: '2022-4-19',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2022-4-19',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '44,96',
        payer: 'Miha',
        payDate: '2022-4-19',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '11,1',
        payer: 'Nataša',
        payDate: '2022-5-19',
        description: 'Jogurti in jajca',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '20,9',
        payer: 'Miha',
        payDate: '2020-6-19',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-7-19',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '35,6',
        payer: 'Nataša',
        payDate: '2021-7-19',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '213,5',
        payer: 'Miha',
        payDate: '2019-8-19',
        description: 'Cenitev stanovanja',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '31,23',
        payer: 'Nataša',
        payDate: '2019-8-19',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-8-19',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '36,04',
        payer: 'Nataša',
        payDate: '2020-10-19',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Zavarovanje',
        cost: '424,48',
        payer: 'Miha',
        payDate: '2020-11-19',
        description: 'BMW - novo zavarovanje (prestavitev na Nata�o)',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 10,
        payer: 'Nataša',
        payDate: '2020-12-19',
        description: 'Skute in mle�ni izdelki',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '33,31',
        payer: 'Nataša',
        payDate: '2020-1-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '44,14',
        payer: 'Miha',
        payDate: '2021-2-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '23,07',
        payer: 'Miha',
        payDate: '2020-3-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '34,55',
        payer: 'Miha',
        payDate: '2021-3-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '24,1',
        payer: 'Nataša',
        payDate: '2020-4-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 5,
        payer: 'Nataša',
        payDate: '2020-5-20',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2022-6-21',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '39,14',
        payer: 'Nataša',
        payDate: '2022-6-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '29,41',
        payer: 'Nataša',
        payDate: '2020-7-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Internet',
        cost: '8,71',
        payer: 'Nataša',
        payDate: '2019-9-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '27,63',
        payer: 'Nataša',
        payDate: '2019-9-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '35,56',
        payer: 'Nataša',
        payDate: '2021-9-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-9-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '25,89',
        payer: 'Miha',
        payDate: '2020-11-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Clio',
        subCategory: 'Pnevmatike',
        cost: '96,94',
        payer: 'Nataša',
        payDate: '2020-11-20',
        description: 'Gume Clio (Sprednji zimski)',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Registracija',
        cost: '33,4',
        payer: 'Nataša',
        payDate: '2020-11-20',
        description: 'BMW - Prepis in cestnina (Prepis na Nata�o)',
        shared: 'TRUE',
    },
    {
        category: 'Clio',
        subCategory: 'Registracija',
        cost: '105,99',
        payer: 'Nataša',
        payDate: '2020-11-20',
        description: 'Registracij in tehni�ni pregled Clio',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '23,2',
        payer: 'Miha',
        payDate: '2019-12-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Vzdrževanje',
        cost: '1246,98',
        payer: 'Nataša',
        payDate: '2019-12-20',
        description: 'BMW - servis - veriga, jermen, izpuh(fleksibilni del)',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'RTV',
        cost: '12,75',
        payer: 'Nataša',
        payDate: '2021-12-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '36,99',
        payer: 'Nataša',
        payDate: '2021-12-20',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '35,54',
        payer: 'Miha',
        payDate: '2020-1-21',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '48,87',
        payer: 'Miha',
        payDate: '2022-1-21',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '37,6',
        payer: 'Miha',
        payDate: '2020-2-21',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 5,
        payer: 'Nataša',
        payDate: '2020-4-21',
        description: 'Skuta',
        shared: 'TRUE',
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: '15,9',
        payer: 'Nataša',
        payDate: '2022-5-21',
        description: 'Majica �iga',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 15,
        payer: 'Nataša',
        payDate: '2022-5-21',
        description: 'Jagode + kruh',
        shared: 'TRUE',
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: 20,
        payer: 'Miha',
        payDate: '2022-5-21',
        description: 'Majica Jaka',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '18,52',
        payer: 'Miha',
        payDate: '2020-7-21',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '17,4',
        payer: 'Miha',
        payDate: '2021-7-21',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '13,68',
        payer: 'Miha',
        payDate: '2021-8-21',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '14,34',
        payer: 'Miha',
        payDate: '2021-9-21',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '21,39',
        payer: 'Miha',
        payDate: '2020-10-21',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: '162,25',
        payer: 'Miha',
        payDate: '2020-2-22',
        description: 'IKEA: Stoli, kro�niki, lu�...',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '52,61',
        payer: 'Miha',
        payDate: '2022-2-22',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Darila',
        subCategory: 'Prijatelji',
        cost: '50,68',
        payer: 'Nataša',
        payDate: '2022-2-22',
        description: 'Igre - majino darilo',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '26,49',
        payer: 'Miha',
        payDate: '2020-4-22',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: 113,
        payer: 'Miha',
        payDate: '2021-4-22',
        description: 'Lora - Vetmedin',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '27,54',
        payer: 'Miha',
        payDate: '2021-5-22',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '23,92',
        payer: 'Miha',
        payDate: '2021-6-22',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '18,58',
        payer: 'Nataša',
        payDate: '2019-8-22',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '17,98',
        payer: 'Miha',
        payDate: '2020-8-22',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '17,91',
        payer: 'Miha',
        payDate: '2020-9-22',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '16,48',
        payer: 'Miha',
        payDate: '2019-10-22',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '15,48',
        payer: 'Miha',
        payDate: '2021-10-22',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: 67,
        payer: 'Miha',
        payDate: '2021-10-22',
        description: 'Servis pre�i - letni pregled',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '19,84',
        payer: 'Miha',
        payDate: '2019-11-22',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '29,84',
        payer: 'Miha',
        payDate: '2020-12-22',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '24,5',
        payer: 'Miha',
        payDate: '2021-12-22',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 10,
        payer: 'Nataša',
        payDate: '2021-1-23',
        description: 'Skute in jogurti',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Lekarna',
        cost: 15,
        payer: 'Nataša',
        payDate: '2022-1-23',
        description: 'Testi',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '10,5',
        payer: 'Nataša',
        payDate: '2022-1-23',
        description: 'Jogurti, sir, skuta',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '32,17',
        payer: 'Miha',
        payDate: '2021-4-23',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '19,7',
        payer: 'Miha',
        payDate: '2020-5-23',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '20,83',
        payer: 'Miha',
        payDate: '2022-6-23',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '39,46',
        payer: 'Miha',
        payDate: '2019-8-23',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '12,9',
        payer: 'Miha',
        payDate: '2019-8-23',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '22,5',
        payer: 'Miha',
        payDate: '2019-8-23',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Komunala',
        cost: '34,45',
        payer: 'Miha',
        payDate: '2019-9-23',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '37,4',
        payer: 'Nataša',
        payDate: '2021-9-23',
        description: 'Lora - Cardiovet',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '20,45',
        payer: 'Miha',
        payDate: '2021-11-23',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: 60,
        payer: 'Nataša',
        payDate: '2019-12-23',
        description: 'Darilo MH escaperoom',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 40,
        payer: 'Nataša',
        payDate: '2020-12-23',
        description: 'MED',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '32,13',
        payer: 'Nataša',
        payDate: '2020-1-24',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 15,
        payer: 'Nataša',
        payDate: '2021-3-24',
        description: 'Jajca in tr�nica',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: 9,
        payer: 'Nataša',
        payDate: '2021-3-24',
        description: 'Lora - tablete',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '37,06',
        payer: 'Miha',
        payDate: '2022-3-24',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Plin',
        cost: '16,45',
        payer: 'Miha',
        payDate: '2019-9-24',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Pnevmatike',
        cost: '207,5',
        payer: 'Nataša',
        payDate: '2019-10-24',
        description: 'BMW - gume',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Pnevmatike',
        cost: '207,5',
        payer: 'Miha',
        payDate: '2019-10-24',
        description: 'BMW - gume',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '13,22',
        payer: 'Nataša',
        payDate: '2021-11-24',
        description: 'RIBA',
        shared: 'TRUE',
    },
    {
        category: 'Zabava',
        subCategory: 'Igrice',
        cost: '36,11',
        payer: 'Nataša',
        payDate: '2021-11-24',
        description: 'TASTER - PS4',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: 18,
        payer: 'Miha',
        payDate: '2021-11-24',
        description: 'BOUL',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: 25,
        payer: 'Miha',
        payDate: '2022-1-25',
        description: 'Trgovina - �ivila',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Vzdrževanje',
        cost: 515,
        payer: 'Nataša',
        payDate: '2020-2-25',
        description: 'BMW - menjava 4x amortizerji',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '89,5',
        payer: 'Nataša',
        payDate: '2022-3-25',
        description: 'Lora - pregled in zdravila',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '51,6',
        payer: 'Miha',
        payDate: '2022-4-25',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Lekarna',
        cost: 63,
        payer: 'Nataša',
        payDate: '2022-5-25',
        description: 'Dodatki - prehrana Tablete za seme :)',
        shared: 'TRUE',
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: '118,25',
        payer: 'Miha',
        payDate: '2021-9-25',
        description: 'Miha RD',
        shared: 'TRUE',
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: 20,
        payer: 'Miha',
        payDate: '2019-12-25',
        description: 'Darilo otroci Slatna',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Elektrika',
        cost: '39,24',
        payer: 'Miha',
        payDate: '2021-1-26',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: 43,
        payer: 'Miha',
        payDate: '2022-5-26',
        description: 'Lora - zdravila',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '48,27',
        payer: 'Miha',
        payDate: '2020-3-27',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: '2,5',
        payer: 'Nataša',
        payDate: '2020-5-27',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '57,58',
        payer: 'Miha',
        payDate: '2022-5-27',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '23,24',
        payer: 'Miha',
        payDate: '2022-8-27',
        description: 'Rezervni sklad GARA�A (5/6/7/8[22])',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '44,87',
        payer: 'Miha',
        payDate: '2019-9-27',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '59,8',
        payer: 'Nataša',
        payDate: '2021-10-27',
        description: 'Lora - Dialix',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 10,
        payer: 'Nataša',
        payDate: '2020-11-27',
        description: 'Jajca in skuta',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '44,46',
        payer: 'Miha',
        payDate: '2019-12-27',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: 31,
        payer: 'Nataša',
        payDate: '2019-12-27',
        description: 'Notar za Nives',
        shared: 'TRUE',
    },
    {
        category: 'Darila',
        subCategory: 'Družina',
        cost: 16,
        payer: 'Miha',
        payDate: '2019-12-27',
        description: 'Tortice za Anjin rojstni dan',
        shared: 'TRUE',
    },
    {
        category: 'Clio',
        subCategory: 'Gorivo',
        cost: 36,
        payer: 'Nataša',
        payDate: '2020-12-27',
        description: 'Bencin - Clio',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '53,44',
        payer: 'Miha',
        payDate: '2020-1-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '46,29',
        payer: 'Miha',
        payDate: '2020-1-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '60,73',
        payer: 'Miha',
        payDate: '2022-1-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '53,57',
        payer: 'Miha',
        payDate: '2020-2-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '69,08',
        payer: 'Miha',
        payDate: '2021-2-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '54,86',
        payer: 'Nataša',
        payDate: '2022-2-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '46,94',
        payer: 'Miha',
        payDate: '2021-3-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '45,74',
        payer: 'Miha',
        payDate: '2022-3-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '32,42',
        payer: 'Nataša',
        payDate: '2022-3-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '40,32',
        payer: 'Miha',
        payDate: '2020-4-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '23,24',
        payer: 'Miha',
        payDate: '2021-4-28',
        description: 'Rezervni sklad GARA�A (1/2/3/4[21])',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '44,89',
        payer: 'Miha',
        payDate: '2021-4-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '23,24',
        payer: 'Miha',
        payDate: '2022-4-28',
        description: 'Rezervni sklad GARA�A (1/2/3/4[22])',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '50,66',
        payer: 'Miha',
        payDate: '2020-5-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '62,33',
        payer: 'Miha',
        payDate: '2021-5-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '42,28',
        payer: 'Miha',
        payDate: '2021-6-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '42,18',
        payer: 'Miha',
        payDate: '2020-7-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '42,33',
        payer: 'Miha',
        payDate: '2021-7-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '38,79',
        payer: 'Miha',
        payDate: '2020-8-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '23,24',
        payer: 'Miha',
        payDate: '2021-8-28',
        description: 'Rezervni sklad GARA�A (5/6/7/8[21])',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '42,75',
        payer: 'Miha',
        payDate: '2021-8-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '45,49',
        payer: 'Miha',
        payDate: '2020-9-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '42,41',
        payer: 'Miha',
        payDate: '2021-9-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '79,88',
        payer: 'Nataša',
        payDate: '2021-9-28',
        description: 'Lora - hrana',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '38,75',
        payer: 'Miha',
        payDate: '2019-10-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '66,08',
        payer: 'Miha',
        payDate: '2020-10-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Tržnica',
        cost: 5,
        payer: 'Nataša',
        payDate: '2020-10-28',
        description: 'Jajca',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '47,58',
        payer: 'Miha',
        payDate: '2021-10-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: '45,14',
        payer: 'Nataša',
        payDate: '2021-10-28',
        description: 'Lora - Klobase',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: 68,
        payer: 'Miha',
        payDate: '2019-11-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '42,75',
        payer: 'Miha',
        payDate: '2021-11-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '56,14',
        payer: 'Miha',
        payDate: '2020-12-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '23,24',
        payer: 'Miha',
        payDate: '2021-12-28',
        description: 'Rezervni sklad GARA�A (9/10/11/12[21])',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '69,99',
        payer: 'Miha',
        payDate: '2021-12-28',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '19,3',
        payer: 'Nataša',
        payDate: '2021-12-28',
        description: 'Lora - zdravila EPATO',
        shared: 'TRUE',
    },
    {
        category: 'Hobi',
        subCategory: 'Plezanje',
        cost: 24,
        payer: 'Nataša',
        payDate: '2021-3-29',
        description: 'Plezanje',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '55,83',
        payer: 'Nataša',
        payDate: '2022-4-29',
        description: 'BMW - Nafta',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '38,17',
        payer: 'Miha',
        payDate: '2020-6-29',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Vzdrževanje',
        cost: 50,
        payer: 'Nataša',
        payDate: '2020-6-29',
        description:
            'BMW - popravilo levega ABS senzorja(podstavitev), dopolnil nivo olja',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: '16,69',
        payer: 'Miha',
        payDate: '2021-9-29',
        description: 'eHrana',
        shared: 'TRUE',
    },
    {
        category: 'Zabava',
        subCategory: 'Knjige',
        cost: 25,
        payer: 'Nataša',
        payDate: '2020-12-29',
        description: 'Knjiga - �tajerski Argo',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: 20,
        payer: 'Nataša',
        payDate: '2022-1-30',
        description: 'Hrana in testi',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: 61,
        payer: 'Nataša',
        payDate: '2021-3-30',
        description: 'Lora - pregled in zdravila',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: '76,66',
        payer: 'Miha',
        payDate: '2022-3-30',
        description: 'BMW - GORIVO',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Restavracije',
        cost: 17,
        payer: 'Miha',
        payDate: '2022-3-30',
        description: 'take out',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '9,5',
        payer: 'Nataša',
        payDate: '2022-4-30',
        description: '�par',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '58,58',
        payer: 'Nataša',
        payDate: '2022-4-30',
        description: 'Hofer',
        shared: 'TRUE',
    },
    {
        category: 'BMW',
        subCategory: 'Gorivo',
        cost: 74,
        payer: 'Miha',
        payDate: '2022-5-30',
        description: 'BMW - Gorivo',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: 45,
        payer: 'Nataša',
        payDate: '2020-9-30',
        description: 'IKEA',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: '47,1',
        payer: 'Nataša',
        payDate: '2021-9-30',
        description: 'Lora - Zdravila',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '14,3',
        payer: 'Nataša',
        payDate: '2021-9-30',
        description: 'SPAR',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '69,82',
        payer: 'Miha',
        payDate: '2020-11-30',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Hrana',
        cost: 88,
        payer: 'Nataša',
        payDate: '2020-12-30',
        description: 'Lora - hrana',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Mercator',
        cost: '9,96',
        payer: 'Nataša',
        payDate: '2021-12-30',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Hofer',
        cost: '50,16',
        payer: 'Nataša',
        payDate: '2021-12-30',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Clio',
        subCategory: 'Gorivo',
        cost: '51,71',
        payer: 'Nataša',
        payDate: '2021-12-30',
        description: 'Clio - tank',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Mercator',
        cost: 20,
        payer: 'Miha',
        payDate: '2021-5-6',
        description: 'Mercator darila Slatna',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Mercator',
        cost: '49,49',
        payer: 'Miha',
        payDate: '2021-5-7',
        description: 'Mercator �okolade in kosilo',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'DM',
        cost: '22,68',
        payer: 'Nataša',
        payDate: '2021-5-8',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: '59,02',
        payer: 'Miha',
        payDate: '2021-5-8',
        description: 'hrana Spar brunch',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '48,92',
        payer: 'Miha',
        payDate: '2021-5-8',
        description: 'Lora - veterinar Lj',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Pregled',
        cost: '18,82',
        payer: 'Miha',
        payDate: '2021-5-8',
        description: 'Lora - veterinar Logatec',
        shared: 'TRUE',
    },
    {
        category: 'Ljubljenčki',
        subCategory: 'Zdravila',
        cost: 14,
        payer: 'Nataša',
        payDate: '2021-5-9',
        description: 'Lora - Lanitop',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Vzdrževanje in nakupi',
        cost: 20,
        payer: 'Nataša',
        payDate: '2022-6-16',
        description: 'IKEA',
        shared: 'TRUE',
    },
    {
        category: 'Hrana',
        subCategory: 'Spar',
        cost: 13,
        payer: 'Nataša',
        payDate: '2022-6-18',
        description: '',
        shared: 'TRUE',
    },
    {
        category: 'Dom',
        subCategory: 'Upravnik',
        cost: '47,19',
        payer: 'Miha',
        payDate: '2022-6-28',
        description: '',
        shared: 'TRUE',
    },
]
